services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal
  aws-cli:
    image: 'amazon/aws-cli:2.0.30'
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./create-table.sh:/usr/local/bin/create-table.sh
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/create-table.sh"]
  nest-app:
    build: .
    command: 'npm run start:dev'
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - aws-cli
    environment:
      DYNAMO_DB_LOCAL_ENDPOINT: 'http://dynamodb-local:8000'
      NODE_ENV: local
      PORT: '3000'
      AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
      AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
      AWS_REGION: us-east-1
      DISABLE_OTEL: y
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./views
          target: /app/views
        - action: rebuild
          path: package.json